### ISSUE TITLE
Project Timeline and MVP Features 

### ISSUE THREAD

**Issue by Harshi-R** [BookNook2023/BookNook#1]
Here are the features and timelines we are thinking of:

MVP Features (By August 31st):
- Homepage 
- User login with authentication 
- Private Bookclub pages that tracks user progress and has announcements 
-Database that stores personal user data (more info coming soon)

Future Features:
-Chat between bookclub members 
-Voting system for next book

**Comment by sais14** [comment]
Figma Link with details: https://www.figma.com/file/Z1ZmKPMCysklZr4TO02yAx/Dream-Book-Club?type=design&mode=design&t=4xTg5G7Hd1dvTcHv-0
